// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xvihztsyyihjkghymudr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2aWh6dHN5eWloamtnaHltdWRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5OTIzNzYsImV4cCI6MjA4ODU2ODM3Nn0.CY5AYSo8xW_uUX7ILRZnCoYIh3ino7UDykCqvp7WRUk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});